### ISSUE TITLE
Rename main branch to master branch

### ISSUE THREAD

**Issue by ghost** [Laus4Deus/nenechi#2]
Rename main branch to master branch

**Comment by Laus4Deus** [comment]
Oh god an actual use of the github!?
Right away. Sorry I did not read it earlier, but as I said a month ago I am very very busy

**Comment by ghost** [comment]
based and Super Hyper Ultra Ultimate Deluxe Perfect Amazing Shining God 東方不敗 Master Ginga Victory Strong Cute Beautiful Galaxy Baby 無限 無敵 無双 Nenechi pilled
